# the name of the job, which must be unique. It is used to store the data for the job
#this field is mandatory
name = "autoscout" 

# path to executable for the job
# this field is mandatory
pathToExecutable = "python3" 

# arguments to be given to the job
# this field is optional
arguments = ["${CONFIGURATION_FILE_PATH}/script.py"] 

# cron string for the job (in this case every other minute, starting at 15 seconds)
# this field is mandatory
cronString = "15 0/2 * ? * * *" 

# tags for this job (metadata for the database)
# this field is optional
tags = ["cars", "vehicles"] 

# how long should Gamayun wait for results of the job before giving up
# this field is optional
resultWaitTimeoutMillis = 10000 

# job will always start randomly somewhere between 0 and 10 seconds after it should be fired by the trigger
# this field is optional
randomTriggerOffsetSeconds = 10 

# each stored result will have unique link field (that is, all documents with the same value under the key link will be considered duplicates). 
# We set the duplicate policy to IGNORE_NEW, which means that if result is reported with link already in DB, it will be ignored
# this field is optional
[duplicateEntryPolicy]
uniqueIds = ["link"] 
onDuplicateEntry = "IGNORE_NEW"

